### ISSUE TITLE
Make assets for Android - icons, splash screens

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#44]
Right now there are only specific icons and splash screens for iOS. I have added a hacky solution that uses the iOS assets, but it would be good to have the right sizes for android.

**Comment by Slava** [comment]
+1

**Comment by stubailo** [comment]
@Slava how are things going with android splash screen support?

**Comment by Slava** [comment]
We need assets tailored for Android requirements.

**Comment by zol** [comment]
@Slava could you please create placeholder assets and configure the android build to use them. I'll have @dominicnguyen create the correct assets.

**Comment by Slava** [comment]
@zol, I am doing other work atm.

**Comment by stubailo** [comment]
For now, can we do the icons only? Those are plain PNGs.

**Comment by zol** [comment]
Yep, I'm on it.

**Comment by zol** [comment]
@stubailo @Slava - I'm trying the app on Android for the first time and getting the following error (latest on the 0.9.4 branch):

Is this a bug?

```
$ meteor android --getready
✓ Java is installed
✓ HAXM is installed
✓ Found Android bundle
✓ Found suitable Android API libraries
✓ 'meteor' android virtual device (AVD) found
sierra:mdg-todos zol$ meteor run android
Error while running for mobile platforms: Error reading mobile-config.js:Error: iphone_2x: unknown key in App.icons configuration.
    at /Users/zol/.meteor/packages/meteor-tool/.1.0.34-pre.11.bio22v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:1255:17
    at Function._.each._.forEach (/Users/zol/.meteor/packages/meteor-tool/.1.0.34-pre.11.bio22v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at Object.App.icons (/Users/zol/.meteor/packages/meteor-tool/.1.0.34-pre.11.bio22v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:1253:9)
    at mobile-config.js:9:5
    at __bottom_mark__ (/Users/zol/.meteor/packages/meteor-tool/.1.0.34-pre.11.bio22v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/parse-stack.js:92:14)
    at Object.files.runJavaScript (/Users/zol/.meteor/packages/meteor-tool/.1.0.34-pre.11.bio22v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/files.js:868:44)
    at consumeControlFile (/Users/zol/.meteor/packages/meteor-tool/.1.0.34-pre.11.bio22v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:1306:11)
    at buildCordova (/Users/zol/.meteor/packages/meteor-tool/.1.0.34-pre.11.bio22v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:729:3)
    at Object.cordova.buildPlatforms (/Users/zol/.meteor/packages/meteor-tool/.1.0.34-pre.11.bio22v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-cordova.js:83:3)
    at doRunCommand [as func] (/Users/zol/.meteor/packages/meteor-tool/.1.0.34-pre.11.bio22v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands.js:243:15)
    at /Users/zol/.meteor/packages/meteor-tool/.1.0.34-pre.11.bio22v++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1245:23
```

**Comment by Slava** [comment]
That's a chance that I made on devel but it is not yet released in an RC. You can either revert my last commit or use checkout meteor.

**Comment by stubailo** [comment]
For now, use the meteor release 0.9.4-rc.1 - we are doing some API changing
for the next RC on the branch.

**Comment by stubailo** [comment]
Disregard my comment, Slava is correct.

**Comment by zol** [comment]
Thanks guys. I just noticed the asset dimensions are all incorrect (for iOS). I'll ask @dominicnguyen  rebuild them including the icons for Android tomorrow (he's out today).

@Slava - Is the plan for `App.icons` and `App.launchScreens` in `mobile-config.js` to support the entire matrix in the Apple [hig](https://developer.apple.com/library/IOs/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html#//apple_ref/doc/uid/TP40006556-CH27-SW1)?

**Comment by zol** [comment]
Android icon sizes:

```
36 × 36 (ldpi)
48 × 48 (mdpi)
72 × 72 (hdpi)
96 × 96 (xhdpi)
```

**Comment by domyen** [comment]
Re-exported iOS icons and exported android icons
https://github.com/percolatestudio/mdg-todos/commit/337ff0ae5ac33d14e706c9bb35ac808f97f1596b
https://github.com/percolatestudio/mdg-todos/commit/78ef87a4885cc9321c42df2ab5bb800afc1d5a41

**Comment by zol** [comment]
Not sure where we're at with branches right now but the assets are fixed and android icons exported on `master` in the above commits.

**Comment by Slava** [comment]
What about splash screens?

**Comment by zol** [comment]
Sashko indicated for the time being we're ok with the icons only. The splashscreens for android are more time consuming to make (because they're 9-patch images)

**Comment by zol** [comment]
@dominicnguyen The cordova docs call for the following splash screen resolution for Android:

```
xlarge (xhdpi): at least 960 × 720
large (hdpi): at least 640 × 480
medium (mdpi): at least 470 × 320
small (ldpi): at least 426 × 320
```

Since we'll be using 9patch images with a centered logo, these dimensions are only a guide. What I actually need is a minimal set of sizes for just the square logo that will work well across all of these dimensions.

**Comment by stubailo** [comment]
I think we still need to convert these into the proper 9-patch format, right?

**Comment by stubailo** [comment]
Also, we should add them to mobile-config.js file and test if they work in the emulator and on at least one device.

**Comment by zol** [comment]
That's right. I'm working on this now.

**Comment by zol** [comment]
@stubailo @Slava - Have you guys ever managed to successfully use a 9-patch splash image? I've definitely followed all documentation and Android just seems to completely ignore the 9-patch nature of whatever splash image I feed it. 

In trying a 'known quantity', I used the guy's image from here: http://www.tidev.io/2014/02/12/android-splash-screens-using-9-patch-images/

And am seeing the following in the emulator:

![screen shot 2014-10-17 at 12 03 56 pm](https://cloud.githubusercontent.com/assets/81672/4684469/ea8f6a22-5630-11e4-8278-ffe031202274.png)

Notice the image is stretched and the dots indicating the 9-patch stretch regions are ignored. (the Cordova class not found error is a separate problem that just started happening).

I'm going to keep investigating but I thought i'd put it out there. Btw, Android is the biggest pain in the arse...

**Comment by Slava** [comment]
@zol internet tells me that it happens because of images being too big (http://stackoverflow.com/questions/25109700/app-crashes-on-android-4-2-out-of-memory-because-of-cordova-splashscreen-plugi - closest link I found in 2mins of googling).

We didn't have 9-patch images so no successful attempts were registered.

**Comment by zol** [comment]
Hmm, that's not the issue. All of the images I've tried (I've tried several 'correct' images from the interwebs) are tiny and none are interpreted as 9 patch. I'm looking closely at this http://community.phonegap.com/nitobi/topics/stretched_9_patch_splash_screens_android thread right now as it seems very related.

**Comment by stubailo** [comment]
Hi, have you tried naming the file with the ".9.png" extension?

**Comment by zol** [comment]
Yep, `splash.9.png`

**Comment by zol** [comment]
@stubailo it appears that the build process moves the file to `screen.png`. This could be why they're not being interpreted correctly. I'm quite confused though as `.meteor/local/cordova-build/platforms/android/res/xml/config.xml` specifies `<splash density="port-ldpi" height="426" src="resources/android_ldpi_portrait.splash.png" width="320" />` and `.meteor/local/cordova-build/platforms/android/res/drawable-land-ldpi` contains `screen.png`. Is `screen.png` a magic name that doesn't have to match up to the `src` attribute in `config.xml`?

**Comment by zol** [comment]
@Slava @stubailo - I think the way meteor configures the android project doesn't work for 9 patch splash screens (the filename not including .9 is likely the issue). Could you please confirm that you can get any old 9 patch splash from the web working e.g from here http://www.tidev.io/2014/02/12/android-splash-screens-using-9-patch-images/ or here http://community.phonegap.com/nitobi/topics/stretched_9_patch_splash_screens_android

Thanks!

**Comment by Slava** [comment]
Is the change committed anywhere on a branch so I can play with it?

**Comment by zol** [comment]
Yes it is. Could you check my github permissions so that I can push it, my
username is 'zol'

**Comment by zol** [comment]
Sorry guys, just needed to accept the permissions from the github email. @Slava I just pushed the `zol-todos-9patch` branch

**Comment by Slava** [comment]
I am confused. Are we working on `meteor/meteor` now for this example?

**Comment by zol** [comment]
Yes, We have moved development over to `meteor/meteor` for todos and
leaderboard.​

**Comment by Slava** [comment]
@zol after a lot of googling and trial and error it looks like setting a 9-patch image is not an option on Cordova 3.x. Everyone is either using a fixed size image or they set these resources from IDEs like Eclipse. http://forum.ionicframework.com/t/need-help-with-displaying-splash-screen-on-android-cordova-3-6/10436/14 - this thread also confirms my findings.

I suggest you pick correct sizes and set the static images (not 9-patch images) for Android splash screens.

**Comment by zol** [comment]
Thanks for looking into it. After wasting a bunch of time on it when developing Verso, I came to the same conclusion. We should update the docs to remove reference to 9 patch so as not to send people astray.

I'll add the splash screens with fixed width.

**Comment by zol** [comment]
```
Cordova-Android original asset dimensions
=========================================

drawable/icon.png: 96 x 96
drawable-hdpi/icon.png: 72 x 72
drawable-ldpi/icon.png: 36 x 36
drawable-mdpi/icon.png: 48 x 48
drawable-xhdpi/icon.png: 96 x 96

drawable-land-hdpi/screen.png: 800 x 480
drawable-land-ldpi/screen.png: 320 x 200
drawable-land-mdpi/screen.png: 480 x 320
drawable-land-xhdpi/screen.png: 1280 x 720
drawable-port-hdpi/screen.png: 480 x 800
drawable-port-ldpi/screen.png: 200 x 320
drawable-port-mdpi/screen.png: 320 x 480
drawable-port-xhdpi/screen.png: 720 x 1280

Cordova-iOS original asset dimensions
=========================================

icons/icon-40.png: 40 x 40
icons/icon-40@2x.png: 80 x 80
icons/icon-50.png: 50 x 50
icons/icon-50@2x.png: 100 x 100
icons/icon-60.png: 60 x 60
icons/icon-60@2x.png: 120 x 120
icons/icon-72.png: 72 x 72
icons/icon-72@2x.png: 144 x 144
icons/icon-76.png: 76 x 76
icons/icon-76@2x.png: 152 x 152
icons/icon-small.png: 29 x 29
icons/icon-small@2x.png: 58 x 58
icons/icon.png: 57 x 57
icons/icon@2x.png: 114 x 114
splash/Default-568h@2x~iphone.png: 640 x 1136
splash/Default-Landscape@2x~ipad.png: 2048 x 1536
splash/Default-Landscape~ipad.png: 1024 x 768
splash/Default-Portrait@2x~ipad.png: 1536 x 2048
splash/Default-Portrait~ipad.png: 768 x 1024
splash/Default@2x~iphone.png: 640 x 960
splash/Default~iphone.png: 320 x 480
```

**Comment by zol** [comment]
Thanks, assets have been created and registered by https://github.com/meteor/meteor/commits/6729b847e260f59d7c91246768529ec0f78b264c

**Comment by krishnaff** [comment]
This is almost 2 years later. 
Is it possible to use 9patch splash screens with Meteor Cordova Android? Tried the .9.png naming, but they don't show up in the device.
Any ideas please?
